# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/design_1_system_ila_1_0.xci
# IP: The module: 'design_1_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/bd_365d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d || ORIG_REF_NAME==bd_365d} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/bd_365d_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_ila_lib_0 || ORIG_REF_NAME==bd_365d_ila_lib_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_1/bd_365d_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_g_inst_0 || ORIG_REF_NAME==bd_365d_g_inst_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_2/bd_365d_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_0_aw_0 || ORIG_REF_NAME==bd_365d_slot_0_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_3/bd_365d_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_0_w_0 || ORIG_REF_NAME==bd_365d_slot_0_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_4/bd_365d_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_0_b_0 || ORIG_REF_NAME==bd_365d_slot_0_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_5/bd_365d_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_0_ar_0 || ORIG_REF_NAME==bd_365d_slot_0_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_6/bd_365d_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_0_r_0 || ORIG_REF_NAME==bd_365d_slot_0_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_7/bd_365d_slot_2_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_2_aw_0 || ORIG_REF_NAME==bd_365d_slot_2_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_8/bd_365d_slot_2_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_2_w_0 || ORIG_REF_NAME==bd_365d_slot_2_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_9/bd_365d_slot_2_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_2_b_0 || ORIG_REF_NAME==bd_365d_slot_2_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_10/bd_365d_slot_2_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_2_ar_0 || ORIG_REF_NAME==bd_365d_slot_2_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_11/bd_365d_slot_2_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_2_r_0 || ORIG_REF_NAME==bd_365d_slot_2_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_12/bd_365d_slot_3_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_3_aw_0 || ORIG_REF_NAME==bd_365d_slot_3_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_13/bd_365d_slot_3_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_3_w_0 || ORIG_REF_NAME==bd_365d_slot_3_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_14/bd_365d_slot_3_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_3_b_0 || ORIG_REF_NAME==bd_365d_slot_3_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_15/bd_365d_slot_3_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_3_ar_0 || ORIG_REF_NAME==bd_365d_slot_3_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_16/bd_365d_slot_3_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_3_r_0 || ORIG_REF_NAME==bd_365d_slot_3_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_17/bd_365d_slot_4_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_4_aw_0 || ORIG_REF_NAME==bd_365d_slot_4_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_18/bd_365d_slot_4_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_4_w_0 || ORIG_REF_NAME==bd_365d_slot_4_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_19/bd_365d_slot_4_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_4_b_0 || ORIG_REF_NAME==bd_365d_slot_4_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_20/bd_365d_slot_4_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_4_ar_0 || ORIG_REF_NAME==bd_365d_slot_4_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_21/bd_365d_slot_4_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_4_r_0 || ORIG_REF_NAME==bd_365d_slot_4_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_22/bd_365d_slot_6_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_6_aw_0 || ORIG_REF_NAME==bd_365d_slot_6_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_23/bd_365d_slot_6_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_6_w_0 || ORIG_REF_NAME==bd_365d_slot_6_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_24/bd_365d_slot_6_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_6_b_0 || ORIG_REF_NAME==bd_365d_slot_6_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_25/bd_365d_slot_6_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_6_ar_0 || ORIG_REF_NAME==bd_365d_slot_6_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_26/bd_365d_slot_6_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_6_r_0 || ORIG_REF_NAME==bd_365d_slot_6_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_27/bd_365d_slot_8_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_8_aw_0 || ORIG_REF_NAME==bd_365d_slot_8_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_28/bd_365d_slot_8_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_8_w_0 || ORIG_REF_NAME==bd_365d_slot_8_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_29/bd_365d_slot_8_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_8_b_0 || ORIG_REF_NAME==bd_365d_slot_8_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_30/bd_365d_slot_8_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_8_ar_0 || ORIG_REF_NAME==bd_365d_slot_8_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_31/bd_365d_slot_8_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_8_r_0 || ORIG_REF_NAME==bd_365d_slot_8_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_32/bd_365d_slot_9_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_9_aw_0 || ORIG_REF_NAME==bd_365d_slot_9_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_33/bd_365d_slot_9_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_9_w_0 || ORIG_REF_NAME==bd_365d_slot_9_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_34/bd_365d_slot_9_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_9_b_0 || ORIG_REF_NAME==bd_365d_slot_9_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_35/bd_365d_slot_9_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_9_ar_0 || ORIG_REF_NAME==bd_365d_slot_9_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_36/bd_365d_slot_9_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_9_r_0 || ORIG_REF_NAME==bd_365d_slot_9_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_37/bd_365d_slot_10_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_10_aw_0 || ORIG_REF_NAME==bd_365d_slot_10_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_38/bd_365d_slot_10_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_10_w_0 || ORIG_REF_NAME==bd_365d_slot_10_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_39/bd_365d_slot_10_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_10_b_0 || ORIG_REF_NAME==bd_365d_slot_10_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_40/bd_365d_slot_10_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_10_ar_0 || ORIG_REF_NAME==bd_365d_slot_10_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_41/bd_365d_slot_10_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_10_r_0 || ORIG_REF_NAME==bd_365d_slot_10_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_42/bd_365d_slot_11_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_11_aw_0 || ORIG_REF_NAME==bd_365d_slot_11_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_43/bd_365d_slot_11_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_11_w_0 || ORIG_REF_NAME==bd_365d_slot_11_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_44/bd_365d_slot_11_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_11_b_0 || ORIG_REF_NAME==bd_365d_slot_11_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_45/bd_365d_slot_11_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_11_ar_0 || ORIG_REF_NAME==bd_365d_slot_11_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_46/bd_365d_slot_11_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_11_r_0 || ORIG_REF_NAME==bd_365d_slot_11_r_0} -quiet] -quiet

# XDC: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_365d_ila_lib_0 || ORIG_REF_NAME==bd_365d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_365d_ila_lib_0 || ORIG_REF_NAME==bd_365d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/bd_365d_ila_lib_0_ooc.xdc

# XDC: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/bd_365d_ooc.xdc

# XDC: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/design_1_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/design_1_system_ila_1_0.xci
# IP: The module: 'design_1_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/bd_365d.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d || ORIG_REF_NAME==bd_365d} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/bd_365d_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_ila_lib_0 || ORIG_REF_NAME==bd_365d_ila_lib_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_1/bd_365d_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_g_inst_0 || ORIG_REF_NAME==bd_365d_g_inst_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_2/bd_365d_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_0_aw_0 || ORIG_REF_NAME==bd_365d_slot_0_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_3/bd_365d_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_0_w_0 || ORIG_REF_NAME==bd_365d_slot_0_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_4/bd_365d_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_0_b_0 || ORIG_REF_NAME==bd_365d_slot_0_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_5/bd_365d_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_0_ar_0 || ORIG_REF_NAME==bd_365d_slot_0_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_6/bd_365d_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_0_r_0 || ORIG_REF_NAME==bd_365d_slot_0_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_7/bd_365d_slot_2_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_2_aw_0 || ORIG_REF_NAME==bd_365d_slot_2_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_8/bd_365d_slot_2_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_2_w_0 || ORIG_REF_NAME==bd_365d_slot_2_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_9/bd_365d_slot_2_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_2_b_0 || ORIG_REF_NAME==bd_365d_slot_2_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_10/bd_365d_slot_2_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_2_ar_0 || ORIG_REF_NAME==bd_365d_slot_2_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_11/bd_365d_slot_2_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_2_r_0 || ORIG_REF_NAME==bd_365d_slot_2_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_12/bd_365d_slot_3_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_3_aw_0 || ORIG_REF_NAME==bd_365d_slot_3_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_13/bd_365d_slot_3_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_3_w_0 || ORIG_REF_NAME==bd_365d_slot_3_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_14/bd_365d_slot_3_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_3_b_0 || ORIG_REF_NAME==bd_365d_slot_3_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_15/bd_365d_slot_3_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_3_ar_0 || ORIG_REF_NAME==bd_365d_slot_3_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_16/bd_365d_slot_3_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_3_r_0 || ORIG_REF_NAME==bd_365d_slot_3_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_17/bd_365d_slot_4_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_4_aw_0 || ORIG_REF_NAME==bd_365d_slot_4_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_18/bd_365d_slot_4_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_4_w_0 || ORIG_REF_NAME==bd_365d_slot_4_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_19/bd_365d_slot_4_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_4_b_0 || ORIG_REF_NAME==bd_365d_slot_4_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_20/bd_365d_slot_4_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_4_ar_0 || ORIG_REF_NAME==bd_365d_slot_4_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_21/bd_365d_slot_4_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_4_r_0 || ORIG_REF_NAME==bd_365d_slot_4_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_22/bd_365d_slot_6_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_6_aw_0 || ORIG_REF_NAME==bd_365d_slot_6_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_23/bd_365d_slot_6_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_6_w_0 || ORIG_REF_NAME==bd_365d_slot_6_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_24/bd_365d_slot_6_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_6_b_0 || ORIG_REF_NAME==bd_365d_slot_6_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_25/bd_365d_slot_6_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_6_ar_0 || ORIG_REF_NAME==bd_365d_slot_6_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_26/bd_365d_slot_6_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_6_r_0 || ORIG_REF_NAME==bd_365d_slot_6_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_27/bd_365d_slot_8_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_8_aw_0 || ORIG_REF_NAME==bd_365d_slot_8_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_28/bd_365d_slot_8_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_8_w_0 || ORIG_REF_NAME==bd_365d_slot_8_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_29/bd_365d_slot_8_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_8_b_0 || ORIG_REF_NAME==bd_365d_slot_8_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_30/bd_365d_slot_8_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_8_ar_0 || ORIG_REF_NAME==bd_365d_slot_8_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_31/bd_365d_slot_8_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_8_r_0 || ORIG_REF_NAME==bd_365d_slot_8_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_32/bd_365d_slot_9_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_9_aw_0 || ORIG_REF_NAME==bd_365d_slot_9_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_33/bd_365d_slot_9_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_9_w_0 || ORIG_REF_NAME==bd_365d_slot_9_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_34/bd_365d_slot_9_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_9_b_0 || ORIG_REF_NAME==bd_365d_slot_9_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_35/bd_365d_slot_9_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_9_ar_0 || ORIG_REF_NAME==bd_365d_slot_9_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_36/bd_365d_slot_9_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_9_r_0 || ORIG_REF_NAME==bd_365d_slot_9_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_37/bd_365d_slot_10_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_10_aw_0 || ORIG_REF_NAME==bd_365d_slot_10_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_38/bd_365d_slot_10_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_10_w_0 || ORIG_REF_NAME==bd_365d_slot_10_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_39/bd_365d_slot_10_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_10_b_0 || ORIG_REF_NAME==bd_365d_slot_10_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_40/bd_365d_slot_10_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_10_ar_0 || ORIG_REF_NAME==bd_365d_slot_10_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_41/bd_365d_slot_10_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_10_r_0 || ORIG_REF_NAME==bd_365d_slot_10_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_42/bd_365d_slot_11_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_11_aw_0 || ORIG_REF_NAME==bd_365d_slot_11_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_43/bd_365d_slot_11_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_11_w_0 || ORIG_REF_NAME==bd_365d_slot_11_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_44/bd_365d_slot_11_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_11_b_0 || ORIG_REF_NAME==bd_365d_slot_11_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_45/bd_365d_slot_11_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_11_ar_0 || ORIG_REF_NAME==bd_365d_slot_11_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_46/bd_365d_slot_11_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_365d_slot_11_r_0 || ORIG_REF_NAME==bd_365d_slot_11_r_0} -quiet] -quiet

# XDC: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_365d_ila_lib_0 || ORIG_REF_NAME==bd_365d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_365d_ila_lib_0 || ORIG_REF_NAME==bd_365d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/bd_365d_ila_lib_0_ooc.xdc

# XDC: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/bd_365d_ooc.xdc

# XDC: /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/design_1_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
