-- Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2017.4 (lin64) Build 2086221 Fri Dec 15 20:54:30 MST 2017
-- Date        : Tue Feb  9 23:11:34 2021
-- Host        : CELSIUS running 64-bit Ubuntu 16.04.7 LTS
-- Command     : write_vhdl -force -mode funcsim
--               /home/duck/Github/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_2/ip/design_2_porttoportmapping_v1_0_0_0/design_2_porttoportmapping_v1_0_0_0_sim_netlist.vhdl
-- Design      : design_2_porttoportmapping_v1_0_0_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xczu9eg-ffvb1156-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity design_2_porttoportmapping_v1_0_0_0 is
  port (
    s00_axi_aclk : in STD_LOGIC;
    s00_axi_aresetn : in STD_LOGIC;
    s00_axi_awid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s00_axi_awaddr : in STD_LOGIC_VECTOR ( 39 downto 0 );
    s00_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s00_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s00_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s00_axi_awlock : in STD_LOGIC;
    s00_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s00_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s00_axi_awqos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s00_axi_awregion : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s00_axi_awuser : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s00_axi_awvalid : in STD_LOGIC;
    s00_axi_awready : out STD_LOGIC;
    s00_axi_wdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    s00_axi_wstrb : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s00_axi_wlast : in STD_LOGIC;
    s00_axi_wvalid : in STD_LOGIC;
    s00_axi_wready : out STD_LOGIC;
    s00_axi_bid : out STD_LOGIC_VECTOR ( 15 downto 0 );
    s00_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s00_axi_bvalid : out STD_LOGIC;
    s00_axi_bready : in STD_LOGIC;
    s00_axi_arid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s00_axi_araddr : in STD_LOGIC_VECTOR ( 39 downto 0 );
    s00_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s00_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s00_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s00_axi_arlock : in STD_LOGIC;
    s00_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s00_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s00_axi_arqos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s00_axi_arregion : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s00_axi_aruser : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s00_axi_arvalid : in STD_LOGIC;
    s00_axi_arready : out STD_LOGIC;
    s00_axi_rid : out STD_LOGIC_VECTOR ( 15 downto 0 );
    s00_axi_rdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    s00_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s00_axi_rlast : out STD_LOGIC;
    s00_axi_rvalid : out STD_LOGIC;
    s00_axi_rready : in STD_LOGIC;
    m00_axi_aclk : in STD_LOGIC;
    m00_axi_aresetn : in STD_LOGIC;
    m00_axi_awid : out STD_LOGIC_VECTOR ( 15 downto 0 );
    m00_axi_awaddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    m00_axi_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m00_axi_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m00_axi_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m00_axi_awlock : out STD_LOGIC;
    m00_axi_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m00_axi_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m00_axi_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m00_axi_awuser : out STD_LOGIC_VECTOR ( 0 to 0 );
    m00_axi_awvalid : out STD_LOGIC;
    m00_axi_awready : in STD_LOGIC;
    m00_axi_wdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    m00_axi_wstrb : out STD_LOGIC_VECTOR ( 15 downto 0 );
    m00_axi_wlast : out STD_LOGIC;
    m00_axi_wvalid : out STD_LOGIC;
    m00_axi_wready : in STD_LOGIC;
    m00_axi_bid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    m00_axi_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m00_axi_bvalid : in STD_LOGIC;
    m00_axi_bready : out STD_LOGIC;
    m00_axi_arid : out STD_LOGIC_VECTOR ( 15 downto 0 );
    m00_axi_araddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    m00_axi_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m00_axi_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m00_axi_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m00_axi_arlock : out STD_LOGIC;
    m00_axi_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m00_axi_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m00_axi_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m00_axi_aruser : out STD_LOGIC_VECTOR ( 0 to 0 );
    m00_axi_arvalid : out STD_LOGIC;
    m00_axi_arready : in STD_LOGIC;
    m00_axi_rid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    m00_axi_rdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    m00_axi_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m00_axi_rlast : in STD_LOGIC;
    m00_axi_rvalid : in STD_LOGIC;
    m00_axi_rready : out STD_LOGIC
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of design_2_porttoportmapping_v1_0_0_0 : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of design_2_porttoportmapping_v1_0_0_0 : entity is "design_2_porttoportmapping_v1_0_0_0,porttoportmapping_v1_0,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of design_2_porttoportmapping_v1_0_0_0 : entity is "yes";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of design_2_porttoportmapping_v1_0_0_0 : entity is "porttoportmapping_v1_0,Vivado 2017.4";
end design_2_porttoportmapping_v1_0_0_0;

architecture STRUCTURE of design_2_porttoportmapping_v1_0_0_0 is
  signal \<const0>\ : STD_LOGIC;
  signal \^m00_axi_arready\ : STD_LOGIC;
  signal \^m00_axi_awready\ : STD_LOGIC;
  signal \^m00_axi_bid\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^m00_axi_bresp\ : STD_LOGIC_VECTOR ( 1 downto 0 );
  signal \^m00_axi_bvalid\ : STD_LOGIC;
  signal \^m00_axi_rdata\ : STD_LOGIC_VECTOR ( 127 downto 0 );
  signal \^m00_axi_rid\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^m00_axi_rlast\ : STD_LOGIC;
  signal \^m00_axi_rresp\ : STD_LOGIC_VECTOR ( 1 downto 0 );
  signal \^m00_axi_rvalid\ : STD_LOGIC;
  signal \^m00_axi_wready\ : STD_LOGIC;
  signal \^s00_axi_araddr\ : STD_LOGIC_VECTOR ( 39 downto 0 );
  signal \^s00_axi_arburst\ : STD_LOGIC_VECTOR ( 1 downto 0 );
  signal \^s00_axi_arcache\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^s00_axi_arid\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^s00_axi_arlen\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^s00_axi_arlock\ : STD_LOGIC;
  signal \^s00_axi_arprot\ : STD_LOGIC_VECTOR ( 2 downto 0 );
  signal \^s00_axi_arqos\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^s00_axi_arsize\ : STD_LOGIC_VECTOR ( 2 downto 0 );
  signal \^s00_axi_aruser\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^s00_axi_arvalid\ : STD_LOGIC;
  signal \^s00_axi_awaddr\ : STD_LOGIC_VECTOR ( 39 downto 0 );
  signal \^s00_axi_awburst\ : STD_LOGIC_VECTOR ( 1 downto 0 );
  signal \^s00_axi_awcache\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^s00_axi_awid\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^s00_axi_awlen\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^s00_axi_awlock\ : STD_LOGIC;
  signal \^s00_axi_awprot\ : STD_LOGIC_VECTOR ( 2 downto 0 );
  signal \^s00_axi_awqos\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^s00_axi_awsize\ : STD_LOGIC_VECTOR ( 2 downto 0 );
  signal \^s00_axi_awuser\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^s00_axi_awvalid\ : STD_LOGIC;
  signal \^s00_axi_bready\ : STD_LOGIC;
  signal \^s00_axi_rready\ : STD_LOGIC;
  signal \^s00_axi_wdata\ : STD_LOGIC_VECTOR ( 127 downto 0 );
  signal \^s00_axi_wlast\ : STD_LOGIC;
  signal \^s00_axi_wstrb\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^s00_axi_wvalid\ : STD_LOGIC;
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of m00_axi_aclk : signal is "xilinx.com:signal:clock:1.0 m00_axi_aclk CLK";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of m00_axi_aclk : signal is "XIL_INTERFACENAME m00_axi_aclk, ASSOCIATED_BUSIF m00_axi, ASSOCIATED_RESET m00_axi_aresetn, FREQ_HZ 249975000, PHASE 0.000, CLK_DOMAIN design_2_zynq_ultra_ps_e_0_0_pl_clk0";
  attribute X_INTERFACE_INFO of m00_axi_aresetn : signal is "xilinx.com:signal:reset:1.0 m00_axi_aresetn RST";
  attribute X_INTERFACE_PARAMETER of m00_axi_aresetn : signal is "XIL_INTERFACENAME m00_axi_aresetn, POLARITY ACTIVE_LOW";
  attribute X_INTERFACE_INFO of m00_axi_arlock : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARLOCK";
  attribute X_INTERFACE_INFO of m00_axi_arready : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARREADY";
  attribute X_INTERFACE_INFO of m00_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARVALID";
  attribute X_INTERFACE_INFO of m00_axi_awlock : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWLOCK";
  attribute X_INTERFACE_INFO of m00_axi_awready : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWREADY";
  attribute X_INTERFACE_INFO of m00_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWVALID";
  attribute X_INTERFACE_INFO of m00_axi_bready : signal is "xilinx.com:interface:aximm:1.0 m00_axi BREADY";
  attribute X_INTERFACE_INFO of m00_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 m00_axi BVALID";
  attribute X_INTERFACE_INFO of m00_axi_rlast : signal is "xilinx.com:interface:aximm:1.0 m00_axi RLAST";
  attribute X_INTERFACE_INFO of m00_axi_rready : signal is "xilinx.com:interface:aximm:1.0 m00_axi RREADY";
  attribute X_INTERFACE_PARAMETER of m00_axi_rready : signal is "XIL_INTERFACENAME m00_axi, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, NUM_READ_THREADINGS 4, NUM_WRITE_THREADING 4, DATA_WIDTH 128, PROTOCOL AXI4, FREQ_HZ 249975000, ID_WIDTH 16, ADDR_WIDTH 40, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, MAX_BURST_LENGTH 256, PHASE 0.000, CLK_DOMAIN design_2_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0";
  attribute X_INTERFACE_INFO of m00_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 m00_axi RVALID";
  attribute X_INTERFACE_INFO of m00_axi_wlast : signal is "xilinx.com:interface:aximm:1.0 m00_axi WLAST";
  attribute X_INTERFACE_INFO of m00_axi_wready : signal is "xilinx.com:interface:aximm:1.0 m00_axi WREADY";
  attribute X_INTERFACE_INFO of m00_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 m00_axi WVALID";
  attribute X_INTERFACE_INFO of s00_axi_aclk : signal is "xilinx.com:signal:clock:1.0 s00_axi_aclk CLK";
  attribute X_INTERFACE_PARAMETER of s00_axi_aclk : signal is "XIL_INTERFACENAME s00_axi_aclk, ASSOCIATED_BUSIF s00_axi, ASSOCIATED_RESET s00_axi_aresetn, FREQ_HZ 249975000, PHASE 0.000, CLK_DOMAIN design_2_zynq_ultra_ps_e_0_0_pl_clk0";
  attribute X_INTERFACE_INFO of s00_axi_aresetn : signal is "xilinx.com:signal:reset:1.0 s00_axi_aresetn RST";
  attribute X_INTERFACE_PARAMETER of s00_axi_aresetn : signal is "XIL_INTERFACENAME s00_axi_aresetn, POLARITY ACTIVE_LOW";
  attribute X_INTERFACE_INFO of s00_axi_arlock : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARLOCK";
  attribute X_INTERFACE_INFO of s00_axi_arready : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARREADY";
  attribute X_INTERFACE_INFO of s00_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARVALID";
  attribute X_INTERFACE_INFO of s00_axi_awlock : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWLOCK";
  attribute X_INTERFACE_INFO of s00_axi_awready : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWREADY";
  attribute X_INTERFACE_INFO of s00_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWVALID";
  attribute X_INTERFACE_INFO of s00_axi_bready : signal is "xilinx.com:interface:aximm:1.0 s00_axi BREADY";
  attribute X_INTERFACE_INFO of s00_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 s00_axi BVALID";
  attribute X_INTERFACE_INFO of s00_axi_rlast : signal is "xilinx.com:interface:aximm:1.0 s00_axi RLAST";
  attribute X_INTERFACE_INFO of s00_axi_rready : signal is "xilinx.com:interface:aximm:1.0 s00_axi RREADY";
  attribute X_INTERFACE_PARAMETER of s00_axi_rready : signal is "XIL_INTERFACENAME s00_axi, DATA_WIDTH 128, PROTOCOL AXI4, FREQ_HZ 249975000, ID_WIDTH 16, ADDR_WIDTH 40, AWUSER_WIDTH 16, ARUSER_WIDTH 16, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.000, CLK_DOMAIN design_2_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0";
  attribute X_INTERFACE_INFO of s00_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 s00_axi RVALID";
  attribute X_INTERFACE_INFO of s00_axi_wlast : signal is "xilinx.com:interface:aximm:1.0 s00_axi WLAST";
  attribute X_INTERFACE_INFO of s00_axi_wready : signal is "xilinx.com:interface:aximm:1.0 s00_axi WREADY";
  attribute X_INTERFACE_INFO of s00_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 s00_axi WVALID";
  attribute X_INTERFACE_INFO of m00_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARADDR";
  attribute X_INTERFACE_INFO of m00_axi_arburst : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARBURST";
  attribute X_INTERFACE_INFO of m00_axi_arcache : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARCACHE";
  attribute X_INTERFACE_INFO of m00_axi_arid : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARID";
  attribute X_INTERFACE_INFO of m00_axi_arlen : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARLEN";
  attribute X_INTERFACE_INFO of m00_axi_arprot : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARPROT";
  attribute X_INTERFACE_INFO of m00_axi_arqos : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARQOS";
  attribute X_INTERFACE_INFO of m00_axi_arsize : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARSIZE";
  attribute X_INTERFACE_INFO of m00_axi_aruser : signal is "xilinx.com:interface:aximm:1.0 m00_axi ARUSER";
  attribute X_INTERFACE_INFO of m00_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWADDR";
  attribute X_INTERFACE_INFO of m00_axi_awburst : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWBURST";
  attribute X_INTERFACE_INFO of m00_axi_awcache : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWCACHE";
  attribute X_INTERFACE_INFO of m00_axi_awid : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWID";
  attribute X_INTERFACE_INFO of m00_axi_awlen : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWLEN";
  attribute X_INTERFACE_INFO of m00_axi_awprot : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWPROT";
  attribute X_INTERFACE_INFO of m00_axi_awqos : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWQOS";
  attribute X_INTERFACE_INFO of m00_axi_awsize : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWSIZE";
  attribute X_INTERFACE_INFO of m00_axi_awuser : signal is "xilinx.com:interface:aximm:1.0 m00_axi AWUSER";
  attribute X_INTERFACE_INFO of m00_axi_bid : signal is "xilinx.com:interface:aximm:1.0 m00_axi BID";
  attribute X_INTERFACE_INFO of m00_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 m00_axi BRESP";
  attribute X_INTERFACE_INFO of m00_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 m00_axi RDATA";
  attribute X_INTERFACE_INFO of m00_axi_rid : signal is "xilinx.com:interface:aximm:1.0 m00_axi RID";
  attribute X_INTERFACE_INFO of m00_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 m00_axi RRESP";
  attribute X_INTERFACE_INFO of m00_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 m00_axi WDATA";
  attribute X_INTERFACE_INFO of m00_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 m00_axi WSTRB";
  attribute X_INTERFACE_INFO of s00_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARADDR";
  attribute X_INTERFACE_INFO of s00_axi_arburst : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARBURST";
  attribute X_INTERFACE_INFO of s00_axi_arcache : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARCACHE";
  attribute X_INTERFACE_INFO of s00_axi_arid : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARID";
  attribute X_INTERFACE_INFO of s00_axi_arlen : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARLEN";
  attribute X_INTERFACE_INFO of s00_axi_arprot : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARPROT";
  attribute X_INTERFACE_INFO of s00_axi_arqos : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARQOS";
  attribute X_INTERFACE_INFO of s00_axi_arregion : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARREGION";
  attribute X_INTERFACE_INFO of s00_axi_arsize : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARSIZE";
  attribute X_INTERFACE_INFO of s00_axi_aruser : signal is "xilinx.com:interface:aximm:1.0 s00_axi ARUSER";
  attribute X_INTERFACE_INFO of s00_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWADDR";
  attribute X_INTERFACE_INFO of s00_axi_awburst : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWBURST";
  attribute X_INTERFACE_INFO of s00_axi_awcache : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWCACHE";
  attribute X_INTERFACE_INFO of s00_axi_awid : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWID";
  attribute X_INTERFACE_INFO of s00_axi_awlen : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWLEN";
  attribute X_INTERFACE_INFO of s00_axi_awprot : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWPROT";
  attribute X_INTERFACE_INFO of s00_axi_awqos : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWQOS";
  attribute X_INTERFACE_INFO of s00_axi_awregion : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWREGION";
  attribute X_INTERFACE_INFO of s00_axi_awsize : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWSIZE";
  attribute X_INTERFACE_INFO of s00_axi_awuser : signal is "xilinx.com:interface:aximm:1.0 s00_axi AWUSER";
  attribute X_INTERFACE_INFO of s00_axi_bid : signal is "xilinx.com:interface:aximm:1.0 s00_axi BID";
  attribute X_INTERFACE_INFO of s00_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 s00_axi BRESP";
  attribute X_INTERFACE_INFO of s00_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 s00_axi RDATA";
  attribute X_INTERFACE_INFO of s00_axi_rid : signal is "xilinx.com:interface:aximm:1.0 s00_axi RID";
  attribute X_INTERFACE_INFO of s00_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 s00_axi RRESP";
  attribute X_INTERFACE_INFO of s00_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 s00_axi WDATA";
  attribute X_INTERFACE_INFO of s00_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 s00_axi WSTRB";
begin
  \^m00_axi_arready\ <= m00_axi_arready;
  \^m00_axi_awready\ <= m00_axi_awready;
  \^m00_axi_bid\(15 downto 0) <= m00_axi_bid(15 downto 0);
  \^m00_axi_bresp\(1 downto 0) <= m00_axi_bresp(1 downto 0);
  \^m00_axi_bvalid\ <= m00_axi_bvalid;
  \^m00_axi_rdata\(127 downto 0) <= m00_axi_rdata(127 downto 0);
  \^m00_axi_rid\(15 downto 0) <= m00_axi_rid(15 downto 0);
  \^m00_axi_rlast\ <= m00_axi_rlast;
  \^m00_axi_rresp\(1 downto 0) <= m00_axi_rresp(1 downto 0);
  \^m00_axi_rvalid\ <= m00_axi_rvalid;
  \^m00_axi_wready\ <= m00_axi_wready;
  \^s00_axi_araddr\(31 downto 16) <= s00_axi_araddr(31 downto 16);
  \^s00_axi_araddr\(13 downto 0) <= s00_axi_araddr(13 downto 0);
  \^s00_axi_arburst\(1 downto 0) <= s00_axi_arburst(1 downto 0);
  \^s00_axi_arcache\(3 downto 0) <= s00_axi_arcache(3 downto 0);
  \^s00_axi_arid\(15 downto 0) <= s00_axi_arid(15 downto 0);
  \^s00_axi_arlen\(7 downto 0) <= s00_axi_arlen(7 downto 0);
  \^s00_axi_arlock\ <= s00_axi_arlock;
  \^s00_axi_arprot\(2 downto 0) <= s00_axi_arprot(2 downto 0);
  \^s00_axi_arqos\(3 downto 0) <= s00_axi_arqos(3 downto 0);
  \^s00_axi_arsize\(2 downto 0) <= s00_axi_arsize(2 downto 0);
  \^s00_axi_aruser\(0) <= s00_axi_aruser(0);
  \^s00_axi_arvalid\ <= s00_axi_arvalid;
  \^s00_axi_awaddr\(35 downto 16) <= s00_axi_awaddr(35 downto 16);
  \^s00_axi_awaddr\(13 downto 0) <= s00_axi_awaddr(13 downto 0);
  \^s00_axi_awburst\(1 downto 0) <= s00_axi_awburst(1 downto 0);
  \^s00_axi_awcache\(3 downto 0) <= s00_axi_awcache(3 downto 0);
  \^s00_axi_awid\(15 downto 0) <= s00_axi_awid(15 downto 0);
  \^s00_axi_awlen\(7 downto 0) <= s00_axi_awlen(7 downto 0);
  \^s00_axi_awlock\ <= s00_axi_awlock;
  \^s00_axi_awprot\(2 downto 0) <= s00_axi_awprot(2 downto 0);
  \^s00_axi_awqos\(3 downto 0) <= s00_axi_awqos(3 downto 0);
  \^s00_axi_awsize\(2 downto 0) <= s00_axi_awsize(2 downto 0);
  \^s00_axi_awuser\(0) <= s00_axi_awuser(0);
  \^s00_axi_awvalid\ <= s00_axi_awvalid;
  \^s00_axi_bready\ <= s00_axi_bready;
  \^s00_axi_rready\ <= s00_axi_rready;
  \^s00_axi_wdata\(127 downto 0) <= s00_axi_wdata(127 downto 0);
  \^s00_axi_wlast\ <= s00_axi_wlast;
  \^s00_axi_wstrb\(15 downto 0) <= s00_axi_wstrb(15 downto 0);
  \^s00_axi_wvalid\ <= s00_axi_wvalid;
  m00_axi_araddr(39) <= \<const0>\;
  m00_axi_araddr(38) <= \<const0>\;
  m00_axi_araddr(37) <= \<const0>\;
  m00_axi_araddr(36) <= \<const0>\;
  m00_axi_araddr(35) <= \<const0>\;
  m00_axi_araddr(34) <= \<const0>\;
  m00_axi_araddr(33) <= \<const0>\;
  m00_axi_araddr(32) <= \<const0>\;
  m00_axi_araddr(31) <= \<const0>\;
  m00_axi_araddr(30) <= \<const0>\;
  m00_axi_araddr(29 downto 14) <= \^s00_axi_araddr\(31 downto 16);
  m00_axi_araddr(13 downto 0) <= \^s00_axi_araddr\(13 downto 0);
  m00_axi_arburst(1 downto 0) <= \^s00_axi_arburst\(1 downto 0);
  m00_axi_arcache(3 downto 0) <= \^s00_axi_arcache\(3 downto 0);
  m00_axi_arid(15 downto 0) <= \^s00_axi_arid\(15 downto 0);
  m00_axi_arlen(7 downto 0) <= \^s00_axi_arlen\(7 downto 0);
  m00_axi_arlock <= \^s00_axi_arlock\;
  m00_axi_arprot(2 downto 0) <= \^s00_axi_arprot\(2 downto 0);
  m00_axi_arqos(3 downto 0) <= \^s00_axi_arqos\(3 downto 0);
  m00_axi_arsize(2 downto 0) <= \^s00_axi_arsize\(2 downto 0);
  m00_axi_aruser(0) <= \^s00_axi_aruser\(0);
  m00_axi_arvalid <= \^s00_axi_arvalid\;
  m00_axi_awaddr(39) <= \<const0>\;
  m00_axi_awaddr(38) <= \<const0>\;
  m00_axi_awaddr(37) <= \<const0>\;
  m00_axi_awaddr(36) <= \<const0>\;
  m00_axi_awaddr(35 downto 32) <= \^s00_axi_awaddr\(35 downto 32);
  m00_axi_awaddr(31) <= \<const0>\;
  m00_axi_awaddr(30) <= \<const0>\;
  m00_axi_awaddr(29 downto 14) <= \^s00_axi_awaddr\(31 downto 16);
  m00_axi_awaddr(13 downto 0) <= \^s00_axi_awaddr\(13 downto 0);
  m00_axi_awburst(1 downto 0) <= \^s00_axi_awburst\(1 downto 0);
  m00_axi_awcache(3 downto 0) <= \^s00_axi_awcache\(3 downto 0);
  m00_axi_awid(15 downto 0) <= \^s00_axi_awid\(15 downto 0);
  m00_axi_awlen(7 downto 0) <= \^s00_axi_awlen\(7 downto 0);
  m00_axi_awlock <= \^s00_axi_awlock\;
  m00_axi_awprot(2 downto 0) <= \^s00_axi_awprot\(2 downto 0);
  m00_axi_awqos(3 downto 0) <= \^s00_axi_awqos\(3 downto 0);
  m00_axi_awsize(2 downto 0) <= \^s00_axi_awsize\(2 downto 0);
  m00_axi_awuser(0) <= \^s00_axi_awuser\(0);
  m00_axi_awvalid <= \^s00_axi_awvalid\;
  m00_axi_bready <= \^s00_axi_bready\;
  m00_axi_rready <= \^s00_axi_rready\;
  m00_axi_wdata(127 downto 0) <= \^s00_axi_wdata\(127 downto 0);
  m00_axi_wlast <= \^s00_axi_wlast\;
  m00_axi_wstrb(15 downto 0) <= \^s00_axi_wstrb\(15 downto 0);
  m00_axi_wvalid <= \^s00_axi_wvalid\;
  s00_axi_arready <= \^m00_axi_arready\;
  s00_axi_awready <= \^m00_axi_awready\;
  s00_axi_bid(15 downto 0) <= \^m00_axi_bid\(15 downto 0);
  s00_axi_bresp(1 downto 0) <= \^m00_axi_bresp\(1 downto 0);
  s00_axi_bvalid <= \^m00_axi_bvalid\;
  s00_axi_rdata(127 downto 0) <= \^m00_axi_rdata\(127 downto 0);
  s00_axi_rid(15 downto 0) <= \^m00_axi_rid\(15 downto 0);
  s00_axi_rlast <= \^m00_axi_rlast\;
  s00_axi_rresp(1 downto 0) <= \^m00_axi_rresp\(1 downto 0);
  s00_axi_rvalid <= \^m00_axi_rvalid\;
  s00_axi_wready <= \^m00_axi_wready\;
GND: unisim.vcomponents.GND
     port map (
      G => \<const0>\
    );
end STRUCTURE;
