# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/design_5_system_ila_0_0.xci
# IP: The module: 'design_5_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/bd_350e.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e || ORIG_REF_NAME==bd_350e} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_0/bd_350e_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_ila_lib_0 || ORIG_REF_NAME==bd_350e_ila_lib_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_1/bd_350e_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_g_inst_0 || ORIG_REF_NAME==bd_350e_g_inst_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_2/bd_350e_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_0_aw_0 || ORIG_REF_NAME==bd_350e_slot_0_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_3/bd_350e_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_0_w_0 || ORIG_REF_NAME==bd_350e_slot_0_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_4/bd_350e_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_0_b_0 || ORIG_REF_NAME==bd_350e_slot_0_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_5/bd_350e_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_0_ar_0 || ORIG_REF_NAME==bd_350e_slot_0_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_6/bd_350e_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_0_r_0 || ORIG_REF_NAME==bd_350e_slot_0_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_7/bd_350e_slot_1_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_1_aw_0 || ORIG_REF_NAME==bd_350e_slot_1_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_8/bd_350e_slot_1_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_1_w_0 || ORIG_REF_NAME==bd_350e_slot_1_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_9/bd_350e_slot_1_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_1_b_0 || ORIG_REF_NAME==bd_350e_slot_1_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_10/bd_350e_slot_1_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_1_ar_0 || ORIG_REF_NAME==bd_350e_slot_1_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_11/bd_350e_slot_1_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_1_r_0 || ORIG_REF_NAME==bd_350e_slot_1_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_12/bd_350e_slot_2_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_2_aw_0 || ORIG_REF_NAME==bd_350e_slot_2_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_13/bd_350e_slot_2_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_2_w_0 || ORIG_REF_NAME==bd_350e_slot_2_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_14/bd_350e_slot_2_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_2_b_0 || ORIG_REF_NAME==bd_350e_slot_2_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_15/bd_350e_slot_2_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_2_ar_0 || ORIG_REF_NAME==bd_350e_slot_2_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_16/bd_350e_slot_2_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_2_r_0 || ORIG_REF_NAME==bd_350e_slot_2_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_17/bd_350e_slot_3_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_3_aw_0 || ORIG_REF_NAME==bd_350e_slot_3_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_18/bd_350e_slot_3_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_3_w_0 || ORIG_REF_NAME==bd_350e_slot_3_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_19/bd_350e_slot_3_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_3_b_0 || ORIG_REF_NAME==bd_350e_slot_3_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_20/bd_350e_slot_3_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_3_ar_0 || ORIG_REF_NAME==bd_350e_slot_3_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_21/bd_350e_slot_3_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_3_r_0 || ORIG_REF_NAME==bd_350e_slot_3_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_22/bd_350e_slot_4_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_4_aw_0 || ORIG_REF_NAME==bd_350e_slot_4_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_23/bd_350e_slot_4_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_4_w_0 || ORIG_REF_NAME==bd_350e_slot_4_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_24/bd_350e_slot_4_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_4_b_0 || ORIG_REF_NAME==bd_350e_slot_4_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_25/bd_350e_slot_4_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_4_ar_0 || ORIG_REF_NAME==bd_350e_slot_4_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_26/bd_350e_slot_4_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_4_r_0 || ORIG_REF_NAME==bd_350e_slot_4_r_0} -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_350e_ila_lib_0 || ORIG_REF_NAME==bd_350e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_350e_ila_lib_0 || ORIG_REF_NAME==bd_350e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_0/bd_350e_ila_lib_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/bd_350e_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/design_5_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_5_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/design_5_system_ila_0_0.xci
# IP: The module: 'design_5_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/bd_350e.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e || ORIG_REF_NAME==bd_350e} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_0/bd_350e_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_ila_lib_0 || ORIG_REF_NAME==bd_350e_ila_lib_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_1/bd_350e_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_g_inst_0 || ORIG_REF_NAME==bd_350e_g_inst_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_2/bd_350e_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_0_aw_0 || ORIG_REF_NAME==bd_350e_slot_0_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_3/bd_350e_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_0_w_0 || ORIG_REF_NAME==bd_350e_slot_0_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_4/bd_350e_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_0_b_0 || ORIG_REF_NAME==bd_350e_slot_0_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_5/bd_350e_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_0_ar_0 || ORIG_REF_NAME==bd_350e_slot_0_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_6/bd_350e_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_0_r_0 || ORIG_REF_NAME==bd_350e_slot_0_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_7/bd_350e_slot_1_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_1_aw_0 || ORIG_REF_NAME==bd_350e_slot_1_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_8/bd_350e_slot_1_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_1_w_0 || ORIG_REF_NAME==bd_350e_slot_1_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_9/bd_350e_slot_1_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_1_b_0 || ORIG_REF_NAME==bd_350e_slot_1_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_10/bd_350e_slot_1_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_1_ar_0 || ORIG_REF_NAME==bd_350e_slot_1_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_11/bd_350e_slot_1_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_1_r_0 || ORIG_REF_NAME==bd_350e_slot_1_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_12/bd_350e_slot_2_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_2_aw_0 || ORIG_REF_NAME==bd_350e_slot_2_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_13/bd_350e_slot_2_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_2_w_0 || ORIG_REF_NAME==bd_350e_slot_2_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_14/bd_350e_slot_2_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_2_b_0 || ORIG_REF_NAME==bd_350e_slot_2_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_15/bd_350e_slot_2_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_2_ar_0 || ORIG_REF_NAME==bd_350e_slot_2_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_16/bd_350e_slot_2_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_2_r_0 || ORIG_REF_NAME==bd_350e_slot_2_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_17/bd_350e_slot_3_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_3_aw_0 || ORIG_REF_NAME==bd_350e_slot_3_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_18/bd_350e_slot_3_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_3_w_0 || ORIG_REF_NAME==bd_350e_slot_3_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_19/bd_350e_slot_3_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_3_b_0 || ORIG_REF_NAME==bd_350e_slot_3_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_20/bd_350e_slot_3_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_3_ar_0 || ORIG_REF_NAME==bd_350e_slot_3_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_21/bd_350e_slot_3_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_3_r_0 || ORIG_REF_NAME==bd_350e_slot_3_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_22/bd_350e_slot_4_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_4_aw_0 || ORIG_REF_NAME==bd_350e_slot_4_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_23/bd_350e_slot_4_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_4_w_0 || ORIG_REF_NAME==bd_350e_slot_4_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_24/bd_350e_slot_4_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_4_b_0 || ORIG_REF_NAME==bd_350e_slot_4_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_25/bd_350e_slot_4_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_4_ar_0 || ORIG_REF_NAME==bd_350e_slot_4_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_26/bd_350e_slot_4_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_350e_slot_4_r_0 || ORIG_REF_NAME==bd_350e_slot_4_r_0} -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_350e_ila_lib_0 || ORIG_REF_NAME==bd_350e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_350e_ila_lib_0 || ORIG_REF_NAME==bd_350e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/ip/ip_0/bd_350e_ila_lib_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/bd_0/bd_350e_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_system_ila_0_0/design_5_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_5_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
