# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design_2_wrapper.xdc

# Block Designs: bd/design_3/design_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3} -quiet] -quiet

# IP: bd/design_3/ip/design_3_zynq_ultra_ps_e_0_0/design_3_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_3_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_porttoportmapping_v1_0_0_0/design_3_porttoportmapping_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_porttoportmapping_v1_0_0_0 || ORIG_REF_NAME==design_3_porttoportmapping_v1_0_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_AXI_PerfectTranslator_0_0/design_3_AXI_PerfectTranslator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_AXI_PerfectTranslator_0_0 || ORIG_REF_NAME==design_3_AXI_PerfectTranslator_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_rst_ps8_0_99M_0/design_3_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_3_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_system_ila_0_0/design_3_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_system_ila_0_0 || ORIG_REF_NAME==design_3_system_ila_0_0} -quiet] -quiet

# XDC: bd/design_3/design_3_ooc.xdc
