# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design_2_wrapper.xdc

# Block Designs: bd/design_5/design_5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5 || ORIG_REF_NAME==design_5} -quiet] -quiet

# IP: bd/design_5/ip/design_5_zynq_ultra_ps_e_0_0/design_5_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_5_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_smartconnect_0_0/design_5_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_smartconnect_0_0 || ORIG_REF_NAME==design_5_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_rst_ps8_0_99M_0/design_5_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_5_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_AXI_PerfectTranslator_0_2/design_5_AXI_PerfectTranslator_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_AXI_PerfectTranslator_0_2 || ORIG_REF_NAME==design_5_AXI_PerfectTranslator_0_2} -quiet] -quiet

# IP: bd/design_5/ip/design_5_AXI_PerfectTranslator_0_3/design_5_AXI_PerfectTranslator_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_AXI_PerfectTranslator_0_3 || ORIG_REF_NAME==design_5_AXI_PerfectTranslator_0_3} -quiet] -quiet

# IP: bd/design_5/ip/design_5_system_ila_0_0/design_5_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_system_ila_0_0 || ORIG_REF_NAME==design_5_system_ila_0_0} -quiet] -quiet

# XDC: bd/design_5/design_5_ooc.xdc
