#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Feb 27 14:40:11 CET 2020
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim TN_NonAXIDomain_behav -key {Behavioral:sim_1:Functional:TN_NonAXIDomain} -tclbatch TN_NonAXIDomain.tcl -view /home/duck/Github/MemorEDF/rtl/ip_repo/src/TB_ConfigurationPort_behav.wcfg -log simulate.log
