webtalk_init -webtalk_dir /home/duck/Github/MemorEDF/rtl/MemorEDF/MemorEDF.tmp/MemorEDF_v1_0_project/MemorEDF_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/TN_NonAXIDomain_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 28 11:23:06 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "942ac98e-cab7-480f-82c0-98ee692534d7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e3c62336ef234b74b725755c2f072240" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "72" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1212.780 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1730 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "133216_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1000443988 -regid "" -xml /home/duck/Github/MemorEDF/rtl/MemorEDF/MemorEDF.tmp/MemorEDF_v1_0_project/MemorEDF_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/TN_NonAXIDomain_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/duck/Github/MemorEDF/rtl/MemorEDF/MemorEDF.tmp/MemorEDF_v1_0_project/MemorEDF_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/TN_NonAXIDomain_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/duck/Github/MemorEDF/rtl/MemorEDF/MemorEDF.tmp/MemorEDF_v1_0_project/MemorEDF_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/TN_NonAXIDomain_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
