#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Feb 20 18:42:45 EST 2021
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim VIP_static_bleacher_behav -key {Behavioral:sim_1:Functional:VIP_static_bleacher} -tclbatch VIP_static_bleacher.tcl -view /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/TB_ConfigurationPort_behav.wcfg -log simulate.log
