# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/design_5_smartconnect_0_0.xci
# IP: The module: 'design_5_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/bd_79ed.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_5/bd_79ed_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_11/bd_79ed_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_12/bd_79ed_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_6/bd_79ed_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_7/bd_79ed_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_8/bd_79ed_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_9/bd_79ed_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_10/bd_79ed_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_2/bd_79ed_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_3/bd_79ed_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_4/bd_79ed_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_0/bd_79ed_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_1/bd_79ed_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_5_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_5/bd_79ed_s00a2s_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_11/bd_79ed_m00s2a_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_6/bd_79ed_sarn_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_7/bd_79ed_srn_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_8/bd_79ed_sawn_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_9/bd_79ed_swn_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_10/bd_79ed_sbn_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_1/bd_79ed_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_1/bd_79ed_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/design_5_smartconnect_0_0.xci
# IP: The module: 'design_5_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/bd_79ed.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_5/bd_79ed_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_11/bd_79ed_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_12/bd_79ed_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_6/bd_79ed_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_7/bd_79ed_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_8/bd_79ed_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_9/bd_79ed_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_10/bd_79ed_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_2/bd_79ed_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_3/bd_79ed_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_4/bd_79ed_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_0/bd_79ed_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_1/bd_79ed_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_5_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_5/bd_79ed_s00a2s_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_11/bd_79ed_m00s2a_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_6/bd_79ed_sarn_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_7/bd_79ed_srn_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_8/bd_79ed_sawn_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_9/bd_79ed_swn_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_10/bd_79ed_sbn_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_1/bd_79ed_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_5/ip/design_5_smartconnect_0_0/bd_0/ip/ip_1/bd_79ed_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.
