# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.cache/wt [current_project]
set_property parent.project_path /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.1 [current_project]
set_property ip_output_repo /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_perf_mon_0_0/design_1_axi_perf_mon_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_perf_mon_0_0/design_1_axi_perf_mon_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_perf_mon_0_0/design_1_axi_perf_mon_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_0/design_1_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_10/bd_886d_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_19/bd_886d_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_25/bd_886d_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_32/bd_886d_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_39/bd_886d_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_46/bd_886d_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_53/bd_886d_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_60/bd_886d_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_61/bd_886d_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_62/bd_886d_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_63/bd_886d_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_64/bd_886d_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_65/bd_886d_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_54/bd_886d_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_55/bd_886d_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_56/bd_886d_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_57/bd_886d_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_58/bd_886d_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_47/bd_886d_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_48/bd_886d_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_49/bd_886d_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_50/bd_886d_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_51/bd_886d_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_40/bd_886d_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_41/bd_886d_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_42/bd_886d_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_43/bd_886d_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_44/bd_886d_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_33/bd_886d_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_34/bd_886d_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_35/bd_886d_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_36/bd_886d_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_37/bd_886d_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_26/bd_886d_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_27/bd_886d_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_28/bd_886d_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_29/bd_886d_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_30/bd_886d_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_20/bd_886d_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_21/bd_886d_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_22/bd_886d_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_23/bd_886d_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_24/bd_886d_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_11/bd_886d_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_12/bd_886d_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_13/bd_886d_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_14/bd_886d_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_15/bd_886d_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_2/bd_886d_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_3/bd_886d_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_4/bd_886d_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_5/bd_886d_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_6/bd_886d_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_1/design_1_axis_subset_converter_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_traffic_gen_0_0/design_1_axi_traffic_gen_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_traffic_gen_0_0/design_1_axi_traffic_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/design_1_axi_dma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/design_1_axi_dma_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/design_1_axi_dma_1_0_clocks.xdc]
set_property used_in_synthesis false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/bd_365d_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/bd_0/bd_365d_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_0/design_1_system_ila_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_bram_0_1/design_1_axi_bram_ctrl_1_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_10/bd_88fd_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_19/bd_88fd_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_28/bd_88fd_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_34/bd_88fd_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_35/bd_88fd_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_36/bd_88fd_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_37/bd_88fd_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_38/bd_88fd_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_39/bd_88fd_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_29/bd_88fd_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_30/bd_88fd_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_31/bd_88fd_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_32/bd_88fd_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_33/bd_88fd_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_20/bd_88fd_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_21/bd_88fd_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_22/bd_88fd_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_23/bd_88fd_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_24/bd_88fd_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_11/bd_88fd_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_12/bd_88fd_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_13/bd_88fd_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_14/bd_88fd_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_15/bd_88fd_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_2/bd_88fd_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_3/bd_88fd_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_4/bd_88fd_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_5/bd_88fd_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_6/bd_88fd_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_2_0/design_1_axi_bram_ctrl_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_10/bd_880d_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_17/bd_880d_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_24/bd_880d_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_30/bd_880d_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_31/bd_880d_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_32/bd_880d_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_33/bd_880d_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_34/bd_880d_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_35/bd_880d_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_25/bd_880d_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_26/bd_880d_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_27/bd_880d_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_28/bd_880d_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_29/bd_880d_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_18/bd_880d_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_19/bd_880d_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_20/bd_880d_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_11/bd_880d_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_12/bd_880d_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_13/bd_880d_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_2/bd_880d_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_3/bd_880d_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_4/bd_880d_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_5/bd_880d_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_6/bd_880d_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_1/bd_880d_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_1/bd_880d_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_2_bram_0/design_1_axi_bram_ctrl_2_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_1/design_1_axi_dma_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_1/design_1_axi_dma_1_1.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_1/design_1_axi_dma_1_1_clocks.xdc]
set_property used_in_synthesis false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/bd_f60c_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/design_1_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/renato/MemorEDF_old/Vivado_Projects/APM_TRACE/APM_TRACE.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
