# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/design_4_system_ila_0_1.xci
# IP: The module: 'design_4_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/bd_650e.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e || ORIG_REF_NAME==bd_650e} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_0/bd_650e_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_ila_lib_0 || ORIG_REF_NAME==bd_650e_ila_lib_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_1/bd_650e_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_g_inst_0 || ORIG_REF_NAME==bd_650e_g_inst_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_2/bd_650e_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_0_aw_0 || ORIG_REF_NAME==bd_650e_slot_0_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_3/bd_650e_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_0_w_0 || ORIG_REF_NAME==bd_650e_slot_0_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_4/bd_650e_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_0_b_0 || ORIG_REF_NAME==bd_650e_slot_0_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_5/bd_650e_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_0_ar_0 || ORIG_REF_NAME==bd_650e_slot_0_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_6/bd_650e_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_0_r_0 || ORIG_REF_NAME==bd_650e_slot_0_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_7/bd_650e_slot_1_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_1_aw_0 || ORIG_REF_NAME==bd_650e_slot_1_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_8/bd_650e_slot_1_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_1_w_0 || ORIG_REF_NAME==bd_650e_slot_1_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_9/bd_650e_slot_1_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_1_b_0 || ORIG_REF_NAME==bd_650e_slot_1_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_10/bd_650e_slot_1_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_1_ar_0 || ORIG_REF_NAME==bd_650e_slot_1_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_11/bd_650e_slot_1_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_1_r_0 || ORIG_REF_NAME==bd_650e_slot_1_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_12/bd_650e_slot_2_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_2_aw_0 || ORIG_REF_NAME==bd_650e_slot_2_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_13/bd_650e_slot_2_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_2_w_0 || ORIG_REF_NAME==bd_650e_slot_2_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_14/bd_650e_slot_2_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_2_b_0 || ORIG_REF_NAME==bd_650e_slot_2_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_15/bd_650e_slot_2_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_2_ar_0 || ORIG_REF_NAME==bd_650e_slot_2_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_16/bd_650e_slot_2_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_2_r_0 || ORIG_REF_NAME==bd_650e_slot_2_r_0} -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_650e_ila_lib_0 || ORIG_REF_NAME==bd_650e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_650e_ila_lib_0 || ORIG_REF_NAME==bd_650e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_0/bd_650e_ila_lib_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/bd_650e_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/design_4_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/design_4_system_ila_0_1.xci
# IP: The module: 'design_4_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/bd_650e.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e || ORIG_REF_NAME==bd_650e} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_0/bd_650e_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_ila_lib_0 || ORIG_REF_NAME==bd_650e_ila_lib_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_1/bd_650e_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_g_inst_0 || ORIG_REF_NAME==bd_650e_g_inst_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_2/bd_650e_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_0_aw_0 || ORIG_REF_NAME==bd_650e_slot_0_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_3/bd_650e_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_0_w_0 || ORIG_REF_NAME==bd_650e_slot_0_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_4/bd_650e_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_0_b_0 || ORIG_REF_NAME==bd_650e_slot_0_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_5/bd_650e_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_0_ar_0 || ORIG_REF_NAME==bd_650e_slot_0_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_6/bd_650e_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_0_r_0 || ORIG_REF_NAME==bd_650e_slot_0_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_7/bd_650e_slot_1_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_1_aw_0 || ORIG_REF_NAME==bd_650e_slot_1_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_8/bd_650e_slot_1_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_1_w_0 || ORIG_REF_NAME==bd_650e_slot_1_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_9/bd_650e_slot_1_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_1_b_0 || ORIG_REF_NAME==bd_650e_slot_1_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_10/bd_650e_slot_1_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_1_ar_0 || ORIG_REF_NAME==bd_650e_slot_1_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_11/bd_650e_slot_1_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_1_r_0 || ORIG_REF_NAME==bd_650e_slot_1_r_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_12/bd_650e_slot_2_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_2_aw_0 || ORIG_REF_NAME==bd_650e_slot_2_aw_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_13/bd_650e_slot_2_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_2_w_0 || ORIG_REF_NAME==bd_650e_slot_2_w_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_14/bd_650e_slot_2_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_2_b_0 || ORIG_REF_NAME==bd_650e_slot_2_b_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_15/bd_650e_slot_2_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_2_ar_0 || ORIG_REF_NAME==bd_650e_slot_2_ar_0} -quiet] -quiet

# IP: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_16/bd_650e_slot_2_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_650e_slot_2_r_0 || ORIG_REF_NAME==bd_650e_slot_2_r_0} -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_650e_ila_lib_0 || ORIG_REF_NAME==bd_650e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_650e_ila_lib_0 || ORIG_REF_NAME==bd_650e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/ip/ip_0/bd_650e_ila_lib_0_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/bd_0/bd_650e_ooc.xdc

# XDC: /home/renato/MemorEDF/MemorEDF/rtl/MemorEDF/MemorEDF.srcs/sources_1/bd/design_4/ip/design_4_system_ila_0_1/design_4_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
