-- Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2017.4 (lin64) Build 2086221 Fri Dec 15 20:54:30 MST 2017
-- Date        : Thu May 14 23:40:37 2020
-- Host        : buflightdev running 64-bit Ubuntu 16.04.6 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_system_ila_1_0_stub.vhdl
-- Design      : design_1_system_ila_1_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu9eg-ffvb1156-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    clk : in STD_LOGIC;
    SLOT_0_AXI_awaddr : in STD_LOGIC_VECTOR ( 12 downto 0 );
    SLOT_0_AXI_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_0_AXI_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_0_AXI_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_0_AXI_awlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    SLOT_0_AXI_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_0_AXI_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_0_AXI_awqos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_0_AXI_awuser : in STD_LOGIC_VECTOR ( 15 downto 0 );
    SLOT_0_AXI_awvalid : in STD_LOGIC;
    SLOT_0_AXI_awready : in STD_LOGIC;
    SLOT_0_AXI_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_0_AXI_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_0_AXI_wlast : in STD_LOGIC;
    SLOT_0_AXI_wvalid : in STD_LOGIC;
    SLOT_0_AXI_wready : in STD_LOGIC;
    SLOT_0_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_0_AXI_bvalid : in STD_LOGIC;
    SLOT_0_AXI_bready : in STD_LOGIC;
    SLOT_0_AXI_araddr : in STD_LOGIC_VECTOR ( 12 downto 0 );
    SLOT_0_AXI_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_0_AXI_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_0_AXI_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_0_AXI_arlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    SLOT_0_AXI_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_0_AXI_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_0_AXI_arqos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_0_AXI_aruser : in STD_LOGIC_VECTOR ( 15 downto 0 );
    SLOT_0_AXI_arvalid : in STD_LOGIC;
    SLOT_0_AXI_arready : in STD_LOGIC;
    SLOT_0_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_0_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_0_AXI_rlast : in STD_LOGIC;
    SLOT_0_AXI_rvalid : in STD_LOGIC;
    SLOT_0_AXI_rready : in STD_LOGIC;
    SLOT_1_AXIS_tid : in STD_LOGIC_VECTOR ( 0 to 0 );
    SLOT_1_AXIS_tdata : in STD_LOGIC_VECTOR ( 55 downto 0 );
    SLOT_1_AXIS_tstrb : in STD_LOGIC_VECTOR ( 6 downto 0 );
    SLOT_1_AXIS_tlast : in STD_LOGIC;
    SLOT_1_AXIS_tvalid : in STD_LOGIC;
    SLOT_1_AXIS_tready : in STD_LOGIC;
    SLOT_2_AXI_awaddr : in STD_LOGIC_VECTOR ( 9 downto 0 );
    SLOT_2_AXI_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_2_AXI_awvalid : in STD_LOGIC;
    SLOT_2_AXI_awready : in STD_LOGIC;
    SLOT_2_AXI_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_2_AXI_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_2_AXI_wvalid : in STD_LOGIC;
    SLOT_2_AXI_wready : in STD_LOGIC;
    SLOT_2_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_2_AXI_bvalid : in STD_LOGIC;
    SLOT_2_AXI_bready : in STD_LOGIC;
    SLOT_2_AXI_araddr : in STD_LOGIC_VECTOR ( 9 downto 0 );
    SLOT_2_AXI_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_2_AXI_arvalid : in STD_LOGIC;
    SLOT_2_AXI_arready : in STD_LOGIC;
    SLOT_2_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_2_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_2_AXI_rvalid : in STD_LOGIC;
    SLOT_2_AXI_rready : in STD_LOGIC;
    SLOT_3_AXI_awid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    SLOT_3_AXI_awaddr : in STD_LOGIC_VECTOR ( 39 downto 0 );
    SLOT_3_AXI_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_3_AXI_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_3_AXI_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_3_AXI_awlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    SLOT_3_AXI_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_3_AXI_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_3_AXI_awqos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_3_AXI_awuser : in STD_LOGIC_VECTOR ( 15 downto 0 );
    SLOT_3_AXI_awvalid : in STD_LOGIC;
    SLOT_3_AXI_awready : in STD_LOGIC;
    SLOT_3_AXI_wdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    SLOT_3_AXI_wstrb : in STD_LOGIC_VECTOR ( 15 downto 0 );
    SLOT_3_AXI_wlast : in STD_LOGIC;
    SLOT_3_AXI_wvalid : in STD_LOGIC;
    SLOT_3_AXI_wready : in STD_LOGIC;
    SLOT_3_AXI_bid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    SLOT_3_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_3_AXI_bvalid : in STD_LOGIC;
    SLOT_3_AXI_bready : in STD_LOGIC;
    SLOT_3_AXI_arid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    SLOT_3_AXI_araddr : in STD_LOGIC_VECTOR ( 39 downto 0 );
    SLOT_3_AXI_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_3_AXI_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_3_AXI_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_3_AXI_arlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    SLOT_3_AXI_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_3_AXI_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_3_AXI_arqos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_3_AXI_aruser : in STD_LOGIC_VECTOR ( 15 downto 0 );
    SLOT_3_AXI_arvalid : in STD_LOGIC;
    SLOT_3_AXI_arready : in STD_LOGIC;
    SLOT_3_AXI_rid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    SLOT_3_AXI_rdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    SLOT_3_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_3_AXI_rlast : in STD_LOGIC;
    SLOT_3_AXI_rvalid : in STD_LOGIC;
    SLOT_3_AXI_rready : in STD_LOGIC;
    SLOT_4_AXI_awaddr : in STD_LOGIC_VECTOR ( 15 downto 0 );
    SLOT_4_AXI_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_4_AXI_awvalid : in STD_LOGIC;
    SLOT_4_AXI_awready : in STD_LOGIC;
    SLOT_4_AXI_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_4_AXI_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_4_AXI_wvalid : in STD_LOGIC;
    SLOT_4_AXI_wready : in STD_LOGIC;
    SLOT_4_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_4_AXI_bvalid : in STD_LOGIC;
    SLOT_4_AXI_bready : in STD_LOGIC;
    SLOT_4_AXI_araddr : in STD_LOGIC_VECTOR ( 15 downto 0 );
    SLOT_4_AXI_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_4_AXI_arvalid : in STD_LOGIC;
    SLOT_4_AXI_arready : in STD_LOGIC;
    SLOT_4_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_4_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_4_AXI_rvalid : in STD_LOGIC;
    SLOT_4_AXI_rready : in STD_LOGIC;
    SLOT_5_AXIS_tid : in STD_LOGIC_VECTOR ( 0 to 0 );
    SLOT_5_AXIS_tdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    SLOT_5_AXIS_tstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_5_AXIS_tlast : in STD_LOGIC;
    SLOT_5_AXIS_tvalid : in STD_LOGIC;
    SLOT_5_AXIS_tready : in STD_LOGIC;
    SLOT_6_AXI_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_6_AXI_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_6_AXI_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_6_AXI_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_6_AXI_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_6_AXI_awvalid : in STD_LOGIC;
    SLOT_6_AXI_awready : in STD_LOGIC;
    SLOT_6_AXI_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_6_AXI_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_6_AXI_wlast : in STD_LOGIC;
    SLOT_6_AXI_wvalid : in STD_LOGIC;
    SLOT_6_AXI_wready : in STD_LOGIC;
    SLOT_6_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_6_AXI_bvalid : in STD_LOGIC;
    SLOT_6_AXI_bready : in STD_LOGIC;
    SLOT_6_AXI_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_6_AXI_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_6_AXI_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_6_AXI_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_6_AXI_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_6_AXI_arvalid : in STD_LOGIC;
    SLOT_6_AXI_arready : in STD_LOGIC;
    SLOT_6_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_6_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_6_AXI_rlast : in STD_LOGIC;
    SLOT_6_AXI_rvalid : in STD_LOGIC;
    SLOT_6_AXI_rready : in STD_LOGIC;
    SLOT_7_AXIS_tid : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_7_AXIS_tdest : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_7_AXIS_tdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_7_AXIS_tstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_7_AXIS_tkeep : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_7_AXIS_tlast : in STD_LOGIC;
    SLOT_7_AXIS_tuser : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_7_AXIS_tvalid : in STD_LOGIC;
    SLOT_7_AXIS_tready : in STD_LOGIC;
    SLOT_8_AXI_awaddr : in STD_LOGIC_VECTOR ( 9 downto 0 );
    SLOT_8_AXI_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_8_AXI_awvalid : in STD_LOGIC;
    SLOT_8_AXI_awready : in STD_LOGIC;
    SLOT_8_AXI_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_8_AXI_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_8_AXI_wvalid : in STD_LOGIC;
    SLOT_8_AXI_wready : in STD_LOGIC;
    SLOT_8_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_8_AXI_bvalid : in STD_LOGIC;
    SLOT_8_AXI_bready : in STD_LOGIC;
    SLOT_8_AXI_araddr : in STD_LOGIC_VECTOR ( 9 downto 0 );
    SLOT_8_AXI_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_8_AXI_arvalid : in STD_LOGIC;
    SLOT_8_AXI_arready : in STD_LOGIC;
    SLOT_8_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_8_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_8_AXI_rvalid : in STD_LOGIC;
    SLOT_8_AXI_rready : in STD_LOGIC;
    SLOT_9_AXI_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_9_AXI_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_9_AXI_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_9_AXI_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_9_AXI_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_9_AXI_awvalid : in STD_LOGIC;
    SLOT_9_AXI_awready : in STD_LOGIC;
    SLOT_9_AXI_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_9_AXI_wstrb : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_9_AXI_wlast : in STD_LOGIC;
    SLOT_9_AXI_wvalid : in STD_LOGIC;
    SLOT_9_AXI_wready : in STD_LOGIC;
    SLOT_9_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_9_AXI_bvalid : in STD_LOGIC;
    SLOT_9_AXI_bready : in STD_LOGIC;
    SLOT_9_AXI_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_9_AXI_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_9_AXI_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_9_AXI_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_9_AXI_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_9_AXI_arvalid : in STD_LOGIC;
    SLOT_9_AXI_arready : in STD_LOGIC;
    SLOT_9_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_9_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_9_AXI_rlast : in STD_LOGIC;
    SLOT_9_AXI_rvalid : in STD_LOGIC;
    SLOT_9_AXI_rready : in STD_LOGIC;
    SLOT_10_AXI_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_10_AXI_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_10_AXI_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_10_AXI_awvalid : in STD_LOGIC;
    SLOT_10_AXI_awready : in STD_LOGIC;
    SLOT_10_AXI_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    SLOT_10_AXI_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_10_AXI_wlast : in STD_LOGIC;
    SLOT_10_AXI_wvalid : in STD_LOGIC;
    SLOT_10_AXI_wready : in STD_LOGIC;
    SLOT_10_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_10_AXI_bvalid : in STD_LOGIC;
    SLOT_10_AXI_bready : in STD_LOGIC;
    SLOT_10_AXI_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_10_AXI_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_10_AXI_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_10_AXI_arvalid : in STD_LOGIC;
    SLOT_10_AXI_arready : in STD_LOGIC;
    SLOT_10_AXI_rdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    SLOT_10_AXI_rlast : in STD_LOGIC;
    SLOT_10_AXI_rvalid : in STD_LOGIC;
    SLOT_10_AXI_rready : in STD_LOGIC;
    SLOT_11_AXI_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_11_AXI_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_11_AXI_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_11_AXI_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_11_AXI_awvalid : in STD_LOGIC;
    SLOT_11_AXI_awready : in STD_LOGIC;
    SLOT_11_AXI_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_11_AXI_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SLOT_11_AXI_wlast : in STD_LOGIC;
    SLOT_11_AXI_wvalid : in STD_LOGIC;
    SLOT_11_AXI_wready : in STD_LOGIC;
    SLOT_11_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SLOT_11_AXI_bvalid : in STD_LOGIC;
    SLOT_11_AXI_bready : in STD_LOGIC;
    SLOT_11_AXI_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_11_AXI_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    SLOT_11_AXI_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    SLOT_11_AXI_arvalid : in STD_LOGIC;
    SLOT_11_AXI_arready : in STD_LOGIC;
    SLOT_11_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    SLOT_11_AXI_rlast : in STD_LOGIC;
    SLOT_11_AXI_rvalid : in STD_LOGIC;
    SLOT_11_AXI_rready : in STD_LOGIC;
    resetn : in STD_LOGIC
  );

end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "clk,SLOT_0_AXI_awaddr[12:0],SLOT_0_AXI_awlen[7:0],SLOT_0_AXI_awsize[2:0],SLOT_0_AXI_awburst[1:0],SLOT_0_AXI_awlock[0:0],SLOT_0_AXI_awcache[3:0],SLOT_0_AXI_awprot[2:0],SLOT_0_AXI_awqos[3:0],SLOT_0_AXI_awuser[15:0],SLOT_0_AXI_awvalid,SLOT_0_AXI_awready,SLOT_0_AXI_wdata[31:0],SLOT_0_AXI_wstrb[3:0],SLOT_0_AXI_wlast,SLOT_0_AXI_wvalid,SLOT_0_AXI_wready,SLOT_0_AXI_bresp[1:0],SLOT_0_AXI_bvalid,SLOT_0_AXI_bready,SLOT_0_AXI_araddr[12:0],SLOT_0_AXI_arlen[7:0],SLOT_0_AXI_arsize[2:0],SLOT_0_AXI_arburst[1:0],SLOT_0_AXI_arlock[0:0],SLOT_0_AXI_arcache[3:0],SLOT_0_AXI_arprot[2:0],SLOT_0_AXI_arqos[3:0],SLOT_0_AXI_aruser[15:0],SLOT_0_AXI_arvalid,SLOT_0_AXI_arready,SLOT_0_AXI_rdata[31:0],SLOT_0_AXI_rresp[1:0],SLOT_0_AXI_rlast,SLOT_0_AXI_rvalid,SLOT_0_AXI_rready,SLOT_1_AXIS_tid[0:0],SLOT_1_AXIS_tdata[55:0],SLOT_1_AXIS_tstrb[6:0],SLOT_1_AXIS_tlast,SLOT_1_AXIS_tvalid,SLOT_1_AXIS_tready,SLOT_2_AXI_awaddr[9:0],SLOT_2_AXI_awprot[2:0],SLOT_2_AXI_awvalid,SLOT_2_AXI_awready,SLOT_2_AXI_wdata[31:0],SLOT_2_AXI_wstrb[3:0],SLOT_2_AXI_wvalid,SLOT_2_AXI_wready,SLOT_2_AXI_bresp[1:0],SLOT_2_AXI_bvalid,SLOT_2_AXI_bready,SLOT_2_AXI_araddr[9:0],SLOT_2_AXI_arprot[2:0],SLOT_2_AXI_arvalid,SLOT_2_AXI_arready,SLOT_2_AXI_rdata[31:0],SLOT_2_AXI_rresp[1:0],SLOT_2_AXI_rvalid,SLOT_2_AXI_rready,SLOT_3_AXI_awid[15:0],SLOT_3_AXI_awaddr[39:0],SLOT_3_AXI_awlen[7:0],SLOT_3_AXI_awsize[2:0],SLOT_3_AXI_awburst[1:0],SLOT_3_AXI_awlock[0:0],SLOT_3_AXI_awcache[3:0],SLOT_3_AXI_awprot[2:0],SLOT_3_AXI_awqos[3:0],SLOT_3_AXI_awuser[15:0],SLOT_3_AXI_awvalid,SLOT_3_AXI_awready,SLOT_3_AXI_wdata[127:0],SLOT_3_AXI_wstrb[15:0],SLOT_3_AXI_wlast,SLOT_3_AXI_wvalid,SLOT_3_AXI_wready,SLOT_3_AXI_bid[15:0],SLOT_3_AXI_bresp[1:0],SLOT_3_AXI_bvalid,SLOT_3_AXI_bready,SLOT_3_AXI_arid[15:0],SLOT_3_AXI_araddr[39:0],SLOT_3_AXI_arlen[7:0],SLOT_3_AXI_arsize[2:0],SLOT_3_AXI_arburst[1:0],SLOT_3_AXI_arlock[0:0],SLOT_3_AXI_arcache[3:0],SLOT_3_AXI_arprot[2:0],SLOT_3_AXI_arqos[3:0],SLOT_3_AXI_aruser[15:0],SLOT_3_AXI_arvalid,SLOT_3_AXI_arready,SLOT_3_AXI_rid[15:0],SLOT_3_AXI_rdata[127:0],SLOT_3_AXI_rresp[1:0],SLOT_3_AXI_rlast,SLOT_3_AXI_rvalid,SLOT_3_AXI_rready,SLOT_4_AXI_awaddr[15:0],SLOT_4_AXI_awprot[2:0],SLOT_4_AXI_awvalid,SLOT_4_AXI_awready,SLOT_4_AXI_wdata[31:0],SLOT_4_AXI_wstrb[3:0],SLOT_4_AXI_wvalid,SLOT_4_AXI_wready,SLOT_4_AXI_bresp[1:0],SLOT_4_AXI_bvalid,SLOT_4_AXI_bready,SLOT_4_AXI_araddr[15:0],SLOT_4_AXI_arprot[2:0],SLOT_4_AXI_arvalid,SLOT_4_AXI_arready,SLOT_4_AXI_rdata[31:0],SLOT_4_AXI_rresp[1:0],SLOT_4_AXI_rvalid,SLOT_4_AXI_rready,SLOT_5_AXIS_tid[0:0],SLOT_5_AXIS_tdata[63:0],SLOT_5_AXIS_tstrb[7:0],SLOT_5_AXIS_tlast,SLOT_5_AXIS_tvalid,SLOT_5_AXIS_tready,SLOT_6_AXI_awaddr[31:0],SLOT_6_AXI_awlen[7:0],SLOT_6_AXI_awsize[2:0],SLOT_6_AXI_awcache[3:0],SLOT_6_AXI_awprot[2:0],SLOT_6_AXI_awvalid,SLOT_6_AXI_awready,SLOT_6_AXI_wdata[31:0],SLOT_6_AXI_wstrb[3:0],SLOT_6_AXI_wlast,SLOT_6_AXI_wvalid,SLOT_6_AXI_wready,SLOT_6_AXI_bresp[1:0],SLOT_6_AXI_bvalid,SLOT_6_AXI_bready,SLOT_6_AXI_araddr[31:0],SLOT_6_AXI_arlen[7:0],SLOT_6_AXI_arsize[2:0],SLOT_6_AXI_arcache[3:0],SLOT_6_AXI_arprot[2:0],SLOT_6_AXI_arvalid,SLOT_6_AXI_arready,SLOT_6_AXI_rdata[31:0],SLOT_6_AXI_rresp[1:0],SLOT_6_AXI_rlast,SLOT_6_AXI_rvalid,SLOT_6_AXI_rready,SLOT_7_AXIS_tid[7:0],SLOT_7_AXIS_tdest[7:0],SLOT_7_AXIS_tdata[31:0],SLOT_7_AXIS_tstrb[3:0],SLOT_7_AXIS_tkeep[3:0],SLOT_7_AXIS_tlast,SLOT_7_AXIS_tuser[7:0],SLOT_7_AXIS_tvalid,SLOT_7_AXIS_tready,SLOT_8_AXI_awaddr[9:0],SLOT_8_AXI_awprot[2:0],SLOT_8_AXI_awvalid,SLOT_8_AXI_awready,SLOT_8_AXI_wdata[31:0],SLOT_8_AXI_wstrb[3:0],SLOT_8_AXI_wvalid,SLOT_8_AXI_wready,SLOT_8_AXI_bresp[1:0],SLOT_8_AXI_bvalid,SLOT_8_AXI_bready,SLOT_8_AXI_araddr[9:0],SLOT_8_AXI_arprot[2:0],SLOT_8_AXI_arvalid,SLOT_8_AXI_arready,SLOT_8_AXI_rdata[31:0],SLOT_8_AXI_rresp[1:0],SLOT_8_AXI_rvalid,SLOT_8_AXI_rready,SLOT_9_AXI_awaddr[31:0],SLOT_9_AXI_awlen[7:0],SLOT_9_AXI_awsize[2:0],SLOT_9_AXI_awcache[3:0],SLOT_9_AXI_awprot[2:0],SLOT_9_AXI_awvalid,SLOT_9_AXI_awready,SLOT_9_AXI_wdata[31:0],SLOT_9_AXI_wstrb[2:0],SLOT_9_AXI_wlast,SLOT_9_AXI_wvalid,SLOT_9_AXI_wready,SLOT_9_AXI_bresp[1:0],SLOT_9_AXI_bvalid,SLOT_9_AXI_bready,SLOT_9_AXI_araddr[31:0],SLOT_9_AXI_arlen[7:0],SLOT_9_AXI_arsize[2:0],SLOT_9_AXI_arcache[3:0],SLOT_9_AXI_arprot[2:0],SLOT_9_AXI_arvalid,SLOT_9_AXI_arready,SLOT_9_AXI_rdata[31:0],SLOT_9_AXI_rresp[1:0],SLOT_9_AXI_rlast,SLOT_9_AXI_rvalid,SLOT_9_AXI_rready,SLOT_10_AXI_awaddr[31:0],SLOT_10_AXI_awlen[7:0],SLOT_10_AXI_awsize[2:0],SLOT_10_AXI_awvalid,SLOT_10_AXI_awready,SLOT_10_AXI_wdata[63:0],SLOT_10_AXI_wstrb[7:0],SLOT_10_AXI_wlast,SLOT_10_AXI_wvalid,SLOT_10_AXI_wready,SLOT_10_AXI_bresp[1:0],SLOT_10_AXI_bvalid,SLOT_10_AXI_bready,SLOT_10_AXI_araddr[31:0],SLOT_10_AXI_arlen[7:0],SLOT_10_AXI_arsize[2:0],SLOT_10_AXI_arvalid,SLOT_10_AXI_arready,SLOT_10_AXI_rdata[63:0],SLOT_10_AXI_rlast,SLOT_10_AXI_rvalid,SLOT_10_AXI_rready,SLOT_11_AXI_awaddr[31:0],SLOT_11_AXI_awlen[7:0],SLOT_11_AXI_awsize[2:0],SLOT_11_AXI_awcache[3:0],SLOT_11_AXI_awvalid,SLOT_11_AXI_awready,SLOT_11_AXI_wdata[31:0],SLOT_11_AXI_wstrb[3:0],SLOT_11_AXI_wlast,SLOT_11_AXI_wvalid,SLOT_11_AXI_wready,SLOT_11_AXI_bresp[1:0],SLOT_11_AXI_bvalid,SLOT_11_AXI_bready,SLOT_11_AXI_araddr[31:0],SLOT_11_AXI_arlen[7:0],SLOT_11_AXI_arsize[2:0],SLOT_11_AXI_arvalid,SLOT_11_AXI_arready,SLOT_11_AXI_rdata[31:0],SLOT_11_AXI_rlast,SLOT_11_AXI_rvalid,SLOT_11_AXI_rready,resetn";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "bd_365d,Vivado 2017.4";
begin
end;
